### ISSUE TITLE
Probably parse all inline style blocks too

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#114]
([Originally posted here](https://github.com/peterbe/minimalcss/pull/58#issuecomment-356730109))

----------

I actually thing we should keep this open. The use case isn't a top priority but it's still something we have a great opportunity to solve. Perhaps:
```
$ ./bin/minimalcss.js --inlines URL
```
And it could *just* download each `style` block, using `cheerio`, and compare it against the DOM(s). We're really close to being able to do this.

Also, since we have access to the `document` in puppeteer we have access to `document.styleSheets`.

The question is, what should the "API" (and cli parameters) be for this?

* We could **combine** the inline blocks with all the downloaded external stylesheets into one blob of CSS.
* We could make it ONLY analyze the inline blocks. 
* (Primarily only a concern for the cli) We could make it pretty-print each inline block with a comment like `/* Inline block number 3 */`

Perhaps we start with a basic implementation and worry about the CLI later. E.g.
```javascript
minimalcss
  .minimize({ urls: ['http://peterbecom.dev/css-blocking/ultra-basic.html'], inlines: true })
  .then(result => {
    result.inlines.forEach((block, i) => {
       console.log(`/* Inline style block number ${i + 1} */`)
       console.log(block.finalCss)
       console.log(`/* Used to be ${block.stylesheetContent.length}bytes but is now ${block.finalCss.length} */`)
    })
  })
```

If a site has (and this is not unusual) 1 external `somefatframework.css` and an inline style block, it's extremely unlikely that the bytes savings on the inline style block will be impressive (or even worth it!) but it's nice to see if you have styles in an inline style block that is now never ever used and can be cleaned up. 

----------

Another reason why this might be important is that you might have this:
```html
<html>
<link rel="stylesheet" href="foo.css">
<style>
div.something {
    animation: rotate-dawg infinite 5s;
    font-family: 'Gill Sans', sans-serif;
}
</style>
```
and in `foo.css` you have this:

```css
@keyframe rotate-dawg {
  from {...}
  to {...}
}
@font-face {
    font-family: Gill Sans;
    src: url(....);
}
/* No mention of div.something in this file */
```
Today, if you analyzed that it'd find that the keyframe and the font-face can be removed before there are no CSS selectors, in any of the **external stylesheets**, that needs it.

**Comment by peterbe** [comment]
I wonder, if we can use devtools coverage reporting instead, it'll analyze all inline styles too, no?

**Comment by stereobooster** [comment]
From my experience, devtools coverage is pretty buggy, but yes theoretically it should analyze all CSS.

**Comment by peterbe** [comment]
here's an interesting case. Try to run `minimalcss` on https://reacttraining.com/react-router/ and you'll get an empty string. It's because it has no external `<link>` stylesheets. On the other hand `document.querySelectorAll('style').length` yields **56**.

I don't know if that site is built with styled-components or whatever but I wonder what amount of CSS in all those stylesheets is actually bloated. Perhaps some but unlikely to be near the massive numbers you get when you depend on a CSS framework that is packaged as a big `something.min.css`. 

Also, suppose `minimalcss` could reduce the content of all `style` elements combined text and compared to the DOM (after rendering). What are you going to do with that?? It obviously totally depends on the JS implementation you use to inject these style tags. However, the rendering of the page would need to be blocked on the downloading, parsing and execution of almost all .js and THEN the CSSOM can be useful.

**Comment by stereobooster** [comment]
https://reacttraining.com/react-router/ uses https://github.com/smyte/jsxstyle. As of CSS in JS this is big conversation, I will need sometime to write out all thoughts on that mater

**Comment by peterbe** [comment]
This issue is morphing. I think there's an immediate need to *read* the inline CSS to avoid deleting stuff from the *external* CSS just because things are not mentioned in the external CSS. 

The second need is to be agnostic about what kind of CSS it is. External or inline.
