### ISSUE TITLE
How to handle big inline base64 encoded things?

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#121]
What to do if there is big image or font embedded as base64-encoded string in styles. Should we include it or skip it?

**Comment by peterbe** [comment]
Not sure I understand the question. `minimalcss` doesn't really have an opinion about what actually goes into the CSS. Just about which selectors to keep or not keep. 

The exception is font faces and keyframes. But it only really looks into the CSS meat to figure out if it can delete or keep certain `@font-face ...` or `@keyframe ...`  at-rules.

**Comment by stereobooster** [comment]
> doesn't really have an opinion about what actually goes into the CSS

Yes. What I'm asking if it should have opinion about big inline blobs or not

**Comment by peterbe** [comment]
> should [minimalcss] have opinion about big inline blobs or not

I vote not. 

It's so hard to know if it's there for a reason not. SemanticUI, for example, uses base64 encoded font files instead of using external URLs. That should not be tampered with.

**Comment by stereobooster** [comment]
I would say I do not want really big inline blobs in critical css. We can have threshold for what to consider "big". We can get back to it later.

**Comment by peterbe** [comment]
Mind you, sometimes it's better to pay a little bit extra for a slightly larger critical CSS if it means you *don't* have to make another network request to download some `/static/dot.png` image or something.
