### ISSUE TITLE
URLs in CSS not save GET params

### ISSUE THREAD

**Issue by usebaz** [peterbe/minimalcss#147]
If I have in my css sprites with get params, for caching. After process over minimalcss url`s remain without get params. It caused double resourse load if I also async include all css.

Example, in full css I have css property:
`background: transparent url("../_img/sprite.svg?1518693909462") -294px -542px no-repeat;`

After minimalcss I receive: 
`background: transparent url("/_img/sprite.svg") -294px -542px no-repeat;`

**Expected:**
`background: transparent url("/_img/sprite.svg?1518693909462") -294px -542px no-repeat;`

**Comment by peterbe** [comment]
Fixed as of https://github.com/peterbe/minimalcss/pull/148

And version 0.7.1 now released.

Thank you so much @usebaz ! I hope you find more things to contribute like this.
