### ISSUE TITLE
Exclude Google Fonts from minimizing

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#164]
Another finding: [Google web fonts uses User Agent Sniffing](https://stackoverflow.com/questions/19467122/how-does-google-web-fonts-decide-which-version-of-a-font-to-provide-to-my-browse), so Google fonts css should be left untouched.

**Possible solutions**:

 - keep logic as is, add this issue to the documentation
 - keep logic as is, but warn people about this issue
 - change logic to exclude Google Fonts css, and expose api to exclude other css, and return array of excluded css file

How to host fonts locally:

- https://google-webfonts-helper.herokuapp.com/fonts
- https://github.com/neverpanic/google-font-download

**UPD:** we have `options.skippable`

**Comment by peterbe** [comment]
So basically, we need to advice users about this odd quirk. It'd be quite impure to write a default `options.skippable` function specifically for this. Then what if the user writes his own `options.skippable` and misses this hack?

By the way, thanks for pointing this out! My [hack here](https://github.com/peterbe/django-peterbecom/blob/4ef0fe355efcf90799d9572ea2a3e26ece5a7cf7/peterbecom/base/jinja2/base.html#L17-L22) is clearly wrong then. I need to invite back the `<link>` tag Google Fonts originally gave me. Sigh. 

A big starting step forward is to mention it in the documentation at least.

**Comment by stereobooster** [comment]
Documentation is good enough. WIll close this
