### ISSUE TITLE
Usage with service worker

### ISSUE THREAD

**Issue by kontrollanten** [peterbe/minimalcss#184]
Thanks for a great module!

I tried to use this with a site that uses ServiceWorker but it failed with the following reason

> Error: DOMException: Failed to register a ServiceWorker: No URL is associated with the caller's document.

[It seems to be an issue with puppeteer](https://github.com/GoogleChrome/puppeteer/issues/1193). Is there any way we can workaround this? I thought it would be possible to just send `page._client.send('Network.setBypassServiceWorker', { bypass: true });` or  `page._client.send('ServiceWorker.disable');` but I haven't got it working.

**Comment by kontrollanten** [comment]
I've got it working by this hack in **src/run.js**.

```
239       page.on('pageerror', error => {
240         if (/Failed to register a ServiceWorker/.test(error.message)=== false) {
241           safeReject(error);
242         }
243       });
```

The rows in puppeteer which is throwing this error looks like this
```
 409   _handleException(exceptionDetails) {
 410     const message = helper.getExceptionMessage(exceptionDetails);
 411     this.emit(Page.Events.PageError, new Error(message));
 412   }
```

Which make it hard to identify the error by anything other than the message.

Would it be an option to just log a warning upon this exception?

**Comment by stereobooster** [comment]
Not sure what is your issue. I get "Failed to register a ServiceWorker" with create-react-app based projects when use it with `react-snap` (which in turn uses `minimalcss`) I simplu ignore it.

Do you see some weird side effects or it is just error message? Can you post example project where it is possible to reproduce issue?

**Comment by stereobooster** [comment]
this is how ServiceWorker registration looks like in Create React App based projects

```js
navigator.serviceWorker
  .register(swUrl)
  .then(function(registration) {
    // your code here
  })
  .catch(function(error) {
    // handle error
    console.error('Error during service worker registration:', error);
  });
```

You need to handle this error

**Comment by stereobooster** [comment]
I hope you found the answer. Feel free to reopen.

**Comment by kontrollanten** [comment]
Sorry for opening an issue and then not replying to your feedback.

Here's how to reproduce:

```
git clone https://github.com/kontrollanten/krypto-konverteraren
cd krypto-konverteraren
yarn
yarn start
yarn minimalcss http://localhost:5000 > minimal.css
```

The only output I'll get in **minimal.css** is the error message:

```
yarn run v1.5.1
$ krypto-konverteraren/node_modules/.bin/minimalcss http://localhost:5000
info If you think this is a bug, please open a bug report with the information provided in "krypto-konverteraren/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by stereobooster** [comment]
You need to `yarn add minimalcss --dev` to be able to run `minimalcss` via `yarn`.

Open issue in https://github.com/NekR/offline-plugin and ask how to handle this error on the client. I tried to search through their documentation, but failed to find something useful

**Comment by kontrollanten** [comment]
Okay, thanks for your quick support!
