### ISSUE TITLE
Prevent network request to Google analytics

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#19]
In `reac-snap` I prevent GA request by detecting userAgent. But we can block those requests based on domain name - there is a comment in source in how to do this.

**Comment by peterbe** [comment]
I saw your PR and I love that you're contributing! Even if I don't approve of everything it inspires me to work on this lib more. 

The example of userAgent is a good example. I think it's a mistake to prevent network requests on just domain. That might be enough in *your* case. Or *his*. Or *hers*. `minimalcss` already has some strong opinions about URLs that shouldn't be loaded, which is that images are not needed. 

The most flexible solution is to be able to pass in a callable where the user can decide for herself. E.g.

```javascript
const skippable = request => {
   const url = response.url
   const ct = response.headers['content-type'] || ''
   if (ct === 'something-special') {
      return true
   } 
   if (url.indexOf('special.js') > -1) {
      return true
   }
   // assume to not skip it
  return false
}
const options = { 
  urls: ['http://peterbecom.dev/css-blocking/ultra-basic.html'],
  skippable
 }
minimalcss
  .minimize()
  .then(result => {
    ...
```

And in `src/run.js`, somewhere, we'd do this:
```javascript
page.on('request', request => {
    if (options.skippable && options.skippable(request)) {
      request.abort()
    }
    ...
```

**Comment by stereobooster** [comment]
I see in case of `minimalcss` it probably doesn't make sense to maintain a blacklist, because this is a tool. But I want some kind of default solution for `react-snap` because this is a tool which should work out of the box.

Possible solutions:

1. blacklist
2. block every request to other domain by default + whitelist
3. callback function

Obviously, a callback function is the most flexible solution (for a lib, but not for the tool).

**Comment by peterbe** [comment]
One tricky thing is that if you "import" minimalcss it's obvious how to write a callable function. But if you use the minimalcss cli, it's not obvious. You *could* do something like `./bin/minimalcss --skip www.google-analytics.com --skip tracking.ads.com http://www.example.com` and the cli could convert that list of domains into a function "for you".

**Comment by stereobooster** [comment]
My current focus is on using `minimalcss` as a library. 

This doesn't look like elegant solution:

```sh
./bin/minimalcss --skip www.google-analytics.com --skip tracking.ads.com
```

**Comment by peterbe** [comment]
So what's left is the `--skip` options to the cli.
