### ISSUE TITLE
Deal with CSS 404s gracefully

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#2]
If one of the URLs you try to open is *not* `200` it will throw an error. It needs to do something graceful and user-friendly too if one of the pages you open has a... `<link href="/404.css">`.

**Comment by stereobooster** [comment]
How to handle this error?

1. throw exception
2. ignore and log warning message

**Comment by peterbe** [comment]
Throw error definitely. It's too hidden otherwise. Also, "log warning message" usually means something like `console.warn` and that goes out on stdout, doesn't it so it's likely not noticed. 

After all, the purpose of `minimalcss` is ultimately for speed freaks with sites that are usually already pretty solid but want to squeeze out a couple of extra milliseconds on the first load experience. 

Now, if the user really knows that it's safe to ignore certain CSS URLs he can use the `--skip` on the CLI or write his own callback function in that `options.skippable` that we're working on.

**Comment by peterbe** [comment]
PR there fixed it.
