### ISSUE TITLE
Use some-kind of type validator

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#21]
For example puppeteer uses TypeScript to validate code based on jsdoc annotations https://github.com/GoogleChrome/puppeteer/pull/986

Also flow can do some validation, but not sure if there is puppeteer type definitions.

**Comment by peterbe** [comment]
Are you suggesting that we rewrite it in TypeScript? I wouldn't mind.

**Comment by peterbe** [comment]
Worth thinking about the fact the minimalcss isn't much of a lib. It's just an elaborate script around something much more powerful.

**Comment by stereobooster** [comment]
We can use TypeScript for checking types in JS files. 

> Worth thinking about the fact the minimalcss isn't much of a lib

Exactly. It is very hard to write unit tests, only integration tests make sense. But with type checker we can verify that we avoid **some** class of errors without huge test cases.

**Comment by peterbe** [comment]
Sure. I'm up for it. I've never actually used TypeScript and I'm eager to try it. Will you lead the way?
