### ISSUE TITLE
Disable Service Workers

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#223]
Service Workers are a thing to help the user agent come back. Then, in the hope of not having to download a bunch of stuff over the network again. Just like caching. Since minimalcss starts a new puppeteer Browser "each time" (`minimalcss-server` uses some Browser recycling), there is never any benefit of using a service worker. Disabling it might help reduce bugs and a small performance boost since it doesn't need to consider all the assets that the service worker dictates.

**Comment by peterbe** [comment]
Note-to-self; see https://github.com/GoogleChrome/puppeteer/issues/1396#issuecomment-344848156

**Comment by peterbe** [comment]
@stereobooster Can you think of any reason not to always call `await page._client.send('ServiceWorker.disable')`?

**Comment by peterbe** [comment]
Oh, it might actually be called `await page._client.send('ServiceWorker.stopAllWorkers');`

**Comment by stereobooster** [comment]
No reason I guess. Also `await page._client.send('ServiceWorker.disable')` will disable protocol, not the worker itself (I got confused too)

**Comment by peterbe** [comment]
I tried to mess with `await page._client.send('ServiceWorker.disable') ` and `await page._client.send('ServiceWorker.stopAllWorkers');` and I don't think it matters since puppeteer 1.4.0 (which is our current minimum) doesn't work with that anyway. 

The only solution I've found is 

1. Upgrade puppeteer to at least 1.7.0

2. Run this code:

```javascript
const puppeteer = require('puppeteer');

//const URL = 'https://googlechrome.github.io/samples/service-worker/basic/';
//const URL = 'https://www.peterbe.com/';
const URL = 'https://songsear.ch/';

// enables request interception but allow everything
async function mockPage(page) {
  await page.setRequestInterception(true);
  await page.on('request', req => req.continue());
}

async function main() {
  const browser = await puppeteer.launch({
    headless: false,
    devtools: true,
    args: ['--enable-features=NetworkService']
  });
  const page = await browser.newPage();
  await page._client.send('ServiceWorker.disable');
  //await page._client.send('ServiceWorker.stopAllWorkers');

  await mockPage(page);

  await page.goto(URL);
}

main()
  .then(data => console.log(data))
  .catch(err => console.error(err));
```

If you do that, no service worker is registered and you don't get any errors or warnings and it doesn't bother at all with service workers.

**Comment by peterbe** [comment]
Another thought I had; I think the option/flag should something like "enableServiceWorker[default=false]". Meaning, it's always disabled. 

One crux; if someone does pass in their own `options.puppeteerArgs` (does react-snap do that?) dare we mess with it to add `--enable-features=NetworkService`?

**Comment by stereobooster** [comment]
yes react-snap uses `puppeteerArgs`, especially people who use react-snap in docker

**Comment by peterbe** [comment]
So how do you feel about doing something like this:

```javascript
// line unchanged from https://github.com/peterbe/minimalcss/blob/master/src/run.js#L361
const puppeteerArgs = options.puppeteerArgs || [];
// THIS?
if (!options.enableServiceWorkers) {
  if (!puppeteerArgs.includes('--enable-features=NetworkService')) {
    // Necessary to be able to disable ServerWorkers later.
    puppeteerArgs.push('--enable-features=NetworkService');
  }
}
...

if (!options.enableServiceWorkers) {
  await page._client.send('ServiceWorker.disable');
}
```

That change might not be good enough. We might need to bump puppeteer in `package.json` too.

**Comment by stereobooster** [comment]
This code looks like what I would write

**Comment by peterbe** [comment]
Note-to-self; it's really easy to reproduce:

```bash
~/minimalcss  master ✔                                                                                                                                                                                       
▶ node bin/minimalcss.js https://googlechrome.github.io/samples/service-worker/basic/
Error: DOMException: Failed to register a ServiceWorker: No URL is associated with the caller's document.
    at Page._handleException (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/puppeteer/lib/Page.js:427:38)
    at CDPSession.Page.client.on.exception (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/puppeteer/lib/Page.js:103:60)
    at CDPSession.emit (events.js:182:13)
    at CDPSession._onMessage (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/puppeteer/lib/Connection.js:219:12)
    at Connection._onMessage (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/puppeteer/lib/Connection.js:119:19)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/ws/lib/Receiver.js:165:16)
```
