### ISSUE TITLE
Missing AST error when stylesheet link.href contains a #fragment

### ISSUE THREAD

**Issue by jc275** [peterbe/minimalcss#255]
When a stylesheet `link.href` contains a [\#fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier), `minimalcss` throws:
`Error: Found stylesheets that failed to download (...)`.

This is because the \#fragment is omitted from puppeteer's `response.url()`, so that it doesn't match the expected `href`. As a result, a missing AST is identified, even though the stylesheet was in fact downloaded and parsed.

(I have no idea why stylesheet urls would contain \#fragments, as I understand they're never sent to the server. But... amazon.com has them, so they _might_ be a thing?)

**Comment by peterbe** [comment]
Do you have a URL where this happens?

**Comment by jc275** [comment]
The only one I identified was amazon.com (and its regional variants, e.g. amazon.co.uk).
