### ISSUE TITLE
Upgrade to support puppeteer 0.12.0

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#33]
We're currently testing with [0.10.2](https://github.com/peterbe/minimalcss/blob/bc68fba2c36d18f3963aea923cb628df7d8dfd95/package.json#L30) and there's a [0.12.0 release](https://github.com/GoogleChrome/puppeteer/releases) available.

One important change is that `setRequestInterceptionEnabled` is renamed to `setRequestInterception`.

**Comment by stereobooster** [comment]
fixed

**Comment by peterbe** [comment]
Weird that GitHub didn't close this issue.
