### ISSUE TITLE
Get HTML retrieved by minimalcss 

### ISSUE THREAD

**Issue by gijo-varghese** [peterbe/minimalcss#347]
Is there any way to get the HTML retrieved while generating minimal css?

Right now I've to open the web page twice to get minimal css and extract html (using a custom script)

**Comment by peterbe** [comment]
Inside the core of `minimalcss` it does take snapshots of the DOMs, which it then proceeds to work with to make the `finalCss`. I don't think it would be hard to add to the final returned output some of those DOMs as serialized strings. 
I can help you if you want to attempt to write a simple unit test.
