### ISSUE TITLE
A way to pass browser instance

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#35]
In `react-snap` I already have an instance of browser. It would be nice if I can pass it instead of another being initiated by minimalcss. Would you accept PR?

**Comment by peterbe** [comment]
Sure! So, instead of 
```javascript
const browser = await puppeteer.launch({})
```
We'd optionally get it from the `options` object, right?

**Comment by peterbe** [comment]
Strange that the PR didn't automatically close this issue.
