### ISSUE TITLE
How's this library different from cssCoverage

### ISSUE THREAD

**Issue by gijo-varghese** [peterbe/minimalcss#350]
I recently found an article using `CSSCoverage` to remove unused CSS (and get used css). Full article: https://blog.fullstacktraining.com/remove-unused-css-javascript-code-from-your-project/

With a few lines of code, it generated "minimal css". So how's this library different?

**Comment by peterbe** [comment]
I don't know what the state is of the CSS coverage stuff in Chrome dev tools. At the time this project started it was not only buggy but it was also flawed in that the final CSS might be exclusive to your viewport. Suppose there's a media query or something that shows or hides elements, that'll effect the minimal css according to dev tools. Suppose you took that css and put that into your HTML files, and the next user views your site, if they don't have the same viewport size, the CSS will be broken. 

What would be ideal is if you could use the dev tools's CSS coverage tools when the viewport is ThisSize1, ThatSize2, ThatSize3 and then get a *union* of the CSS needed.

**Comment by peterbe** [comment]
Another thing that `minimalcss` can do is that it can give you the minimal CSS that's needed before *and* **after** the JS has loaded and executed. E.g.

```css
/* foo.css */
blockquote, p { color: pink }
```
```html
<link href=foo.js rel="stylesheet">
<blockquote>Hi, I'm colored pink</blockquote>
<p>also pink</p>
<script>
window.onload = () => {
  var bl = document.querySelector('blockquote')
  bl.parentNode.removeChild(bl)
}
</script>
```
If you'd run that with dev tools it'll tell you that the minimal CSS is:
```css
/* foo.js */
p { color: pink }
```
But if you'd put that into your page like this:
```html
<!-- <link href=foo.js rel="stylesheet"> -->
<style>
p { color: pink }
</style>

<blockquote>Hi, I'm colored pink</blockquote>
<p>also pink</p>
<script>
window.onload = () => {
  var bl = document.querySelector('blockquote')
  bl.parentNode.removeChild(bl)
}
</script>
```
then, your page would be styled differently before and after the JS has executed. Remember, the browser will render out the DOM at least once (after the CSSOM is complete) before the JS effects kick in.
So your users would get a flicker or anything else more disastrous.

**Comment by gijo-varghese** [comment]
Thanks, @peterbe for the detailed reply. I looked into in deep and found many bugs. @font-face, media queries and many other styles are missing in the final css as you said.

**Comment by gijo-varghese** [comment]
@peterbe not exactly related to this thread, but does `minimalcss` crawl the site twice to generate the css before and after executing JavaScript?

**Comment by peterbe** [comment]
> @peterbe not exactly related to this thread, but does `minimalcss` crawl the site twice to generate the css before and after executing JavaScript?

Not "crawl" but it opens the page before and after JS has loaded.

**Comment by gijo-varghese** [comment]
@peterbe will that send requests to the server again?

**Comment by peterbe** [comment]
> @peterbe will that send requests to the server again?

I don't remember right now. Would you mind finding out?

**Comment by gijo-varghese** [comment]
@peterbe if `disableJavaScript` is false, the lines https://github.com/peterbe/minimalcss/blob/ff4af46545573ad2ba4ffc4a1716e49adcabe2a6/src/run.js#L287 and https://github.com/peterbe/minimalcss/blob/ff4af46545573ad2ba4ffc4a1716e49adcabe2a6/src/run.js#L310 will execute right?
