### ISSUE TITLE
Cannot read property 'ok' of null

### ISSUE THREAD

**Issue by ggiak** [peterbe/minimalcss#352]
https://link1 works as a charm
https://link2 works as a charm

when used together, the following error throws:

> Cannot read property 'ok' of null

minimalcss version: 0.9.0

```
const minimalcss = require('minimalcss');
minimalcss
  .minimize({ urls: [
	'https://link1', 
	'https://link2',
	]
	
  })
  .then(result => {
    console.log(result.finalCss);
  })
  .catch(error => {
    console.error(`Failed the minimize CSS: ${error}`);
  });
```

Disabling the website's service worker works!

**Comment by peterbe** [comment]
This, from the root directory of this repo, as of the latest `master` branch:
```javascript
const minimalcss = require('.');
minimalcss
  .minimize({
    urls: [
      'https://developer.mozilla.org/en-US/',
      'https://developer.mozilla.org/fr/'
    ]
  })
  .then(result => {
    console.log(result.finalCss);
  })
  .catch(error => {
    console.error(`Failed the minimize CSS: ${error}`);
  });
```
...works. Spits out a bunch of minimized CSS. 

When you get `Cannot read property 'ok' of null` it usually means that the `chromium` inside `puppeteer` can't even connect. I.e. a complete network failure. But I'm actually not entirely sure of that either. Because when I mess with the domain name in my URL I get:

```
Failed the minimize CSS: Error: net::ERR_NAME_NOT_RESOLVED at https://developer.XXXmozilla.org/en-US/
```
for example.

**Comment by ggiak** [comment]
@peterbe I am not sure.
both of them works when trying this out solo.

also I managed to resolve this after removing my service worker.

Keep that in mind

**Comment by peterbe** [comment]
`minimalcss`, by default, disables all service workers. It's called `enableServiceWorkers`.

**Comment by stereobooster** [comment]
coincidence 

<img width="1417" alt="Screenshot 2020-02-04 at 10 41 54" src="https://user-images.githubusercontent.com/179534/73732744-00c87080-473b-11ea-8c57-9b80ebf8cb27.png">

**Comment by ggiak** [comment]
Looks like few things were sorted out in regard of service workers.
