### ISSUE TITLE
Rewrite URL before making request

### ISSUE THREAD

**Issue by gijo-varghese** [peterbe/minimalcss#356]
In one of the page, the Google Font URL looks like this: `https://fonts.googleapis.com/css?family=Roboto`

I want to add a `display=swap` query param at the end (`https://fonts.googleapis.com/css?family=Roboto&display=swap`) and then only generate minimal css.

Is it possible somehow?

Unfortunately, I can't update the code in the actual site.

**Comment by peterbe** [comment]
It is not possible, but there is [a function that gets executed for each request](https://github.com/peterbe/minimalcss/blob/a549be31ab934655fc63e424287c0426d814743a/src/run.js#L216)
So, the very first thing it does could be something like...

```diff
      page.on('request', request => {
+      if (options.requestInterception) {
+        if (options.requestInterception(request)) {
+            // The extra requestInterception() function returned a truthy value, that means it
+            // dealth with the request itself. 
+            return;
+        }
+      }
        const resourceType = request.resourceType();
        const requestUrl = request.url();
        if (/data:image\//.test(requestUrl)) {
```

What do you think?

**Comment by gijo-varghese** [comment]
@peterbe I solved it by parsing the `finalCss` and injecting necessary values into it.

But I think something like that would be very beneficial.
