### ISSUE TITLE
minimaljs?

### ISSUE THREAD

**Issue by baturkacamak** [peterbe/minimalcss#409]
this is not an issue with a minimalcss directly but couldnt find a better place to ask this.

since minimalcss based on csscoverage of the current page. will there be a version with the same principles of minimalcss for javascript? like minimaljs?

**Comment by peterbe** [comment]
Haha. That would be neat but it's a much more complicated topic. I think the more common term is "tree-shaking" which JavaScript build looks like Rollup and webpack etc. do. But that's just the static-analysis portion. What's cool about this `minimalcss` project is that it's beyond the static analysis but the space for DOM and CSSOM is order of magnitude simpler to reason around compared to JavaScript.
