### ISSUE TITLE
Make a demo server on Heroku

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#41]
See https://timleland.com/headless-chrome-on-heroku/ for tips about buildpacks that work.

**Comment by peterbe** [comment]
Also, see https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-heroku

**Comment by stereobooster** [comment]
I was able to deploy to Heroku https://github.com/stereobooster/an-almost-static-stack/pull/7/files my project with puppeteer

**Comment by peterbe** [comment]
That would be neat! I'd love to see an example of that. 

Mind you, a cool thing about [minimalcss-server](https://github.com/peterbe/minimalcss-server) is that...

* [A global cache for global URLs can benefit repeated lookups](https://github.com/peterbe/minimalcss-server/blob/4311bc63fb8924ae14598462aa3bc2940100784b/server.js#L16-L21)
* [A pool of already created browser instances makes it much faster to load that second, third, etc. run.](https://github.com/peterbe/minimalcss-server/blob/4311bc63fb8924ae14598462aa3bc2940100784b/server.js#L42-L46)

**Comment by tomgallagher** [comment]
Caching could lead to problems with outdated resources, mismatches with new versions of html and js files, etc. Should be OK to cache for a short period.

You'd be surprised probably with how fast Lambda functions can spin up a new version of Chrome for Puppeteer, depending on the memory allocated, less than 10 seconds definitely. Not OK if you're trying to process pages on-the-fly but good for preloading.

**Comment by tomgallagher** [comment]
The other thing about Lambda is the first approx 300,000 iterations per month are free.

**Comment by peterbe** [comment]
Mind you, the `minimalcss-server` code was "selfishly" written to support exactly how I use `minimalcss` in www.peterbe.com. So I'm quite confident around the caching etc. However, it is a bit scary that two distinct people's requests might intermingle. What if the browser instance from one user affects the next user. Yuck. 

Also, a scary thing about how `minimalcss-server` currently works is that it's quite unprotected. What if someone manages to find a URL that is insane and thus the ExpressJS service might explode in memory or CPU. Also it could leak or break so that someone might be able to hack the server. With Lambda, since there's no state (or /etc/passwd or .env files) it'd make me feel a lot safer using it for untrusted people. 

Therefore, I'm really looking forward to seeing a `minimalcss-lambda` project. It could take a couple of ideas from `minimalcss-server` (but no LRU cache or browser pool). Would love to see a prototype like that.

**Comment by peterbe** [comment]
I built https://minimalcss.app instead.
