### ISSUE TITLE
Actually do some e2e testing

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#49]
In https://github.com/peterbe/minimalcss/blob/master/tests/e2e.js it currently just uses puppeteer and doesn't actually use `minimalcss`. It should. And it should execute it in such a way that actually does some real downloads.

**Comment by peterbe** [comment]
Also, ideally in https://github.com/peterbe/minimalcss/blob/master/tests/run.sh there should be a `cli` one that runs `./bin/minimalcss.js ...` and makes sure cli parsing etc works.

**Comment by stereobooster** [comment]
Close in favour of #120?

**Comment by peterbe** [comment]
I'm terrible at looking through old issues when filing new ones.

Let's go for https://github.com/peterbe/minimalcss/issues/120 instead.
