### ISSUE TITLE
Question about size

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#59]
In `react-snap` I compare the size of critical CSS (generated by `minimalcss`) and actual CSS. If the difference is less than 2 times I inline the whole CSS and drop the link at all.

`minimalcss` already have all this data (all rules loaded in memory). **First question**: can `minimalcss` expose this data (critical CSS size vs full size). Do you think this is appropriate functionality for `minimalcss`?

**Second question**. If `react-snap` choose to inline whole CSS instead of `critical` it has the same problems as `minimalcss` - needs to rewrite relative paths etc. I can implement this, but do not want to duplicate functionality. Can `minimalcss` return all CSS in the same format critical?

All this functionality will be exposed through programmatical API, but not CLI. I ask your opinion. If you think this appropriate I will do PRs.

**Comment by peterbe** [comment]
The "critical CSS size" is `result.finalCss.length` in the main promise. The size of the CSS before is the sum of each `result.stylesheetContents`. E.g.
```javascript
minimalcss
  .minimize({ urls: ['http://peterbecom.dev/css-blocking/ultra-basic.html'] })
  .then(result => {
    let before = 0
    Object.keys(result.stylesheetContents).forEach(key => {
       before += result.stylesheetContents[key].length
    })
    console.log('BEFORE', before)
    console.log('AFTER', result.finalCss.length)
    console.log('SAVINGS', before - result.finalCss.length)
})
```
[See the cli code for that](https://github.com/peterbe/minimalcss/blob/31847f7e8aaa2dad60ef4aecd30645dde73297e8/bin/minimalcss.js#L105-L111)

**Comment by peterbe** [comment]
Regarding your second question, "Can minimalcss return all CSS in the same format critical?"
I don't understand that.

**Comment by stereobooster** [comment]
> Can minimalcss return all CSS in the same format critical?

I suppose this is what I want (pseudocode)

```
minimalcss
  .minimize({ urls: ['http://peterbecom.dev/css-blocking/ultra-basic.html'] })
  .then(result => {
    let originalCss = ""
    Object.keys(result.stylesheetContents).forEach(key => {
       originalCss += result.stylesheetContents[key]
    })
    console.log('BEFORE', originalCss)
    console.log('AFTER', result.finalCss)
})
```

**Comment by peterbe** [comment]
That's not pseudo code :) That's working code.

**Comment by stereobooster** [comment]
Oh nice. You solved it for me :)
