### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#60]
Related https://github.com/stereobooster/react-snap/issues/45

Error thrown inside promise is not handled. Probably need catch it and expose as `Promise.reject`

**Comment by peterbe** [comment]
Where is it not handled? Also, isn't it a good thing that a broken JS code blows up because if JS isn't working on the page, how can `minimalcss`, with confidence, know what CSS is needed.

**Comment by stereobooster** [comment]
> Where is it not handled? 

`react-snap` as user of `minimalcss` can not take over error handling

**Comment by peterbe** [comment]
Let's fix that!

**Comment by stereobooster** [comment]
resolved
