### ISSUE TITLE
Fails randomly

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#70]
This is trace from `react-snap`, but it is `minimalcss` is failing. This is two consequent runs.

```
➜  react-snap git:(master) ✗ ./run.js
🕸  (4/4) /
🔥  /css-relative-path.html Error: Evaluation failed: Error: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css not in stylesheetAstObjects!
    at links.filter.forEach.stylesheet (<anonymous>:126:21)
    at Array.forEach (<anonymous>)
    at <anonymous>:124:12
```
```
➜  react-snap git:(master) ✗ ./run.js
🕸  (4/4) /css-relative-path.html
```

html

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link href="images/css-relative-path.css" rel=stylesheet>
    <link href=https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css rel=stylesheet>
  </head>
  <body>
    <p>Only a P tag in this document.</p>
  </body>
</html>
```

I suspect this can be due to network failure

**Comment by peterbe** [comment]
First of all, I need to review your awesome [PR](https://github.com/peterbe/minimalcss/pull/65) for better error handling. 

Secondly, what might have happened is that when puppeteer opened the page (and downloads all stylesheets into memory) it should NOT be acceptable that some of those failed. E.g. if `https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css` temporarily times out, it should throw a loud error.

**Comment by peterbe** [comment]
Any new clues on this? I find it hard to believe that Chromium has a short timeout. 

BUT perhaps our underlying understanding of how [`goto` and `networkidle2`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options) works is wrong. Perhaps puppeteer (and Chromium) triggers the `goto` promise before the triggering of those `page.on('request', ...` events. 

We can, and should revisit this, after the [puppeteer 1.0.0](https://github.com/peterbe/minimalcss/pull/74) upgrade. Perhaps that changes everything and the random failures disappear.

**Comment by stereobooster** [comment]
I want to test with 404 css file for starters

**Comment by peterbe** [comment]
See this comment: https://github.com/peterbe/minimalcss/pull/65#issuecomment-358509997
about 404 css. 

I strongly suspect that's a different topic though. If you example html file works once, it should pretty much always work. Or never work. 

Perhaps it's a race condition somewhere.

**Comment by stereobooster** [comment]
> `networkidle2` - consider navigation to be finished when there are no more than 2 network connections for at least 500 ms.

I consider using `networkidle0` in `react-snap` when I will upgrade

**Comment by stereobooster** [comment]
Confirmed not 404. Maybe empty response due to network failure or race condition

**Comment by stereobooster** [comment]
Have no idea how to debug this. WIll close for now, because not actionable
