### ISSUE TITLE
Document limitations

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#8]
We're basically at the mercy of what [csso](https://github.com/css/csso) can do. For example, it's bound to keep the keyframes even if there's not mention of its *using* as an animation. Sure, we could attempt some hardcode post-processing by logging all animation usage within selector blocks. However, this is bound to be a leaking abstraction that breaks sooner or later.

**Comment by stereobooster** [comment]
need to update status of this ticket

**Comment by peterbe** [comment]
The world is significantly differently these days.
