### ISSUE TITLE
`stylesheetContents` in promise isn't a string

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#80]
[According to our doc string](https://github.com/peterbe/minimalcss/blob/a97fa21c87a47af2bab18a4e4a3f1257fc956a49/src/run.js#L42), the main `minimalcss` function returns a promise. And inside that promise is a dict. But it says that one of the keys in that dict is a string. 
`stylesheetContents` isn't a string returned in the promise. It's a dict where every key is a `.css` file URL and every value is the complete unprocesses raw CSS as a string. 

@stereobooster I guess this is where typescript might have helped if actually used in runtime :)

**Comment by stereobooster** [comment]
TypeScript is very bugy https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+label%3A%22Domain%3A+JSDoc%22, this is why it doesn't catch it
