### ISSUE TITLE
Ditch greenkeeper in favor of Renovate

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#98]
Greenkeeper made [this PR](https://github.com/peterbe/minimalcss/pull/96) and I just merged it. That was stupid. The PR only updates the `package.json` but now makes the `yarn.lock` mismatch. 
So, after I did a `git pull origin master; yarn` the `yarn.lock` is now out of sync. 

Let's stop using Greenkeeper and use [Renovate](https://renovateapp.com/) instead because I know their PRs update `package.json` **and** `yarn.lock`.

**Comment by peterbe** [comment]
I have enabled Renovate as a valid app and I've merged [its first PR](https://github.com/peterbe/minimalcss/pull/97).

**Comment by peterbe** [comment]
Greenkeeper has been removed as an app now.

**Comment by stereobooster** [comment]
this seems to be fixed
